name: Run Smoke Test

on:
  schedule:
    # Every weekday at 5am
    - cron: '0 5 * * 1-5'
  push:

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Step 2 - Set up JDK 11
        uses: actions/setup-java@v2

        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Step 3 - Build with Maven
        env:
          ORCHESTRATOR_STUB_URL: https://build-di-ipv-orchestrator-stub.london.cloudapps.digital/
          BROWSER: chrome-headless
        run:  mvn clean test -D"cucumber.filter.tags=@address_smoke"
